# Name of our workflow - this appears in the GitHub Actions tab
name: Python Linting

# Define when this workflow should run
on: [push, pull_request]  # Runs on every push and pull request

# A workflow can have multiple jobs
jobs:
  lint:  # This job is called "lint"
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v3
      
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # You can specify your Python version
        
    # Step 3: Install required packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    # Step 4: Run Pylint
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=7.0